name: testapp-cicd
run-name: ${{ github.actor }} triggered pipeline with ${{ github.sha }} activity.

on: 
  push:
    branches: 
      - 'release/dev'
  pull_request:
    branches:
      - 'release/dev'
jobs:
  testapp-deployment:
     runs-on: ubuntu-22.04
     environment: dev
     steps:
     - name: 'Checkout GitHub Action' 
       uses: actions/checkout@v3
     - name: 'Login to Azure Container Registry'
       uses: azure/docker-login@v1
       with:
         login-server: ${{ secrets.ACR_SERVER }}
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}
     - name: 'Image build and push to ACR'
       run: |
         docker build . -t ${{ secrets.ACR_SERVER }}/testapp:${{ github.sha }}
         docker push ${{ secrets.ACR_SERVER }}/testapp:${{ github.sha }}

     - name: 'Az CLI login'
       uses: azure/login@v1
       with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

     - name: 'Deploying image to App Service'
       uses: azure/webapps-deploy@v2
       with:
        app-name: 'testapprwdev'
        images: ${{ secrets.ACR_SERVER }}/testapp:${{ github.sha }}
         





   
 
     