name: testapp-cicd
run-name: ${{ github.actor }} triggered pipeline.

on: 
  push:
    branches: 
      - 'release/dev'
  pull_request:
    branches:
      - 'release/dev'
jobs:
  image-build:
     runs-on: ubuntu-22.04
     environment: dev
     steps:
     - uses: actions/checkout@v3
     - uses: azure/docker-login@v1
       with:
         login-server: ${{ secrets.ACR_SERVER }}
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}




   
