name: testapp-cicd
run-name: ${{ github.actor }} triggered pipeline.

on: 
  push:
    branches: 
      - 'release/dev'
  pull_request:
    branches:
      - 'release/dev'
jobs:
   test:
     runs-on: ubuntu-22.04
     steps:
       - run: "🎉 The job was automatically triggered by a ${{ github.event_name }} event."



   
